name: Deploy Azure Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './api/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd api
        npm ci
    
    - name: Build
      run: |
        cd api
        npm run build
    
    - name: Debug Secrets
      run: |
        echo "App name length: ${#AZURE_FUNCTIONAPP_NAME}"
        echo "App name set: $([[ -n "$AZURE_FUNCTIONAPP_NAME" ]] && echo "YES" || echo "NO")"
        echo "Publish profile length: ${#AZURE_FUNCTIONAPP_PUBLISH_PROFILE}"
        echo "Publish profile set: $([[ -n "$AZURE_FUNCTIONAPP_PUBLISH_PROFILE" ]] && echo "YES" || echo "NO")"
      env:
        AZURE_FUNCTIONAPP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
    
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        slot-name: 'production'
        package: './api'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}